global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "lb"

rule_files:

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "lb"
    dns_sd_configs:
      - names: ["lb"]
        port: 8000
        type: A
        refresh_interval: 5s
